language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t bemineni/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bemineni/react-test npm test

after_sucess:
    - docker build -t bemineni/multi-client ./client
    - docker build -t bemineni/multi-nginx ./nginx
    - docker build -t bemineni/multi-server ./server
    - docker build -t bemineni/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker-hub
    - docker push bemineni/multi-client
    - docker push bemineni/multi-nginx
    - docker push bemineni/multi-server
    - docker push bemineni/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region:  "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-840819556522"
    bucket_path: "multi-docker"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
