sudo: required
services:
    - docker

before_install:
    - docker build -t srikanthbemineni/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true srikanthbemineni/react-test npm test

after_sucess:
    - docker build -t srikanthbemineni/multi-client ./client
    - docker build -t srikanthbemineni/multi-nginx ./nginx
    - docker build -t srikanthbemineni/multi-server ./server
    - docker build -t srikanthbemineni/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker-hub
    - docker push srikanthbemineni/multi-client
    - docker push srikanthbemineni/multi-nginx
    - docker push srikanthbemineni/multi-server
    - docker push srikanthbemineni/multi-worker
